# -*- coding: utf-8 -*-
"""Basics_of_Stats2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IwYpllFKa6ysGH6orM6wXq2_V22DMQw3
"""



"""a. Build 99% Confidence Interval Using Sample Standard Deviation
b. Build 99% Confidence Interval Using Known Population Standard Deviation
"""

import numpy as np
import scipy.stats as stats

data = [1.13, 1.55, 1.43, 0.92, 1.25, 1.36, 1.32, 0.85, 1.07, 1.48, 1.20, 1.33, 1.18, 1.22, 1.29]
data = np.array(data)

n = len(data)
sample_mean = np.mean(data)
sample_std = np.std(data, ddof=1)
confidence = 0.99
alpha = 1 - confidence

print(f"Sample Size (n): {n}")
print(f"Sample Mean: {sample_mean:.3f}")
print(f"Sample Standard Deviation: {sample_std:.3f}")

df = n - 1
t_critical = stats.t.ppf(1 - alpha/2, df)
margin_error_t = t_critical * (sample_std / np.sqrt(n))
lower_t = sample_mean - margin_error_t
upper_t = sample_mean + margin_error_t

print("\n(a) 99% Confidence Interval using t-distribution:")
print(f"t-critical value: {t_critical:.4f}")
print(f"Margin of Error: {margin_error_t:.4f}")
print(f"Confidence Interval: ({lower_t:.4f}, {upper_t:.4f})")

pop_std = 0.2
z_critical = stats.norm.ppf(1 - alpha/2)
margin_error_z = z_critical * (pop_std / np.sqrt(n))
lower_z = sample_mean - margin_error_z
upper_z = sample_mean + margin_error_z

print("\n(b) 99% Confidence Interval using z-distribution:")
print(f"z-critical value: {z_critical:.4f}")
print(f"Margin of Error: {margin_error_z:.4f}")
print(f"Confidence Interval: ({lower_z:.4f}, {upper_z:.4f})")